using uTracerProManager.Core.Models;

namespace uTracerProManager.AvaloniaApp.ViewModels;

public sealed class DatabaseProfileEditorViewModel : ObservableObject
{
    private string _profileId="",_displayName="",_family="",_tubeTypes="",_manufacturer="",_warning="",_purpose="",_sourceTitle="",_sourceUrl="",_sourcePage="",_notes="",_heaterMode="INTERNAL_OK",_heaterNote="",_reviewer="",_reviewNote="",_status="Wczytaj profil BLOCKED/PENDING z katalogu.";
    private string? _pinout,_curveGrids;
    private double? _heaterVoltage,_heaterCurrent,_anodeVoltage,_screenVoltage,_gridVoltage,_ia,_is,_gm,_mu,_rp,_maxVa,_maxVs,_maxPa,_maxPs,_iaComp,_isComp,_curveStart,_curveStop,_curveStep;
    private int? _warmup;
    private bool _sourceOk,_pinoutOk,_heaterOk,_pointOk,_limitsOk,_powerOk,_hardwareOk;

    public string ProfileId{get=>_profileId;set=>SetProperty(ref _profileId,value);} public string DisplayName{get=>_displayName;set=>SetProperty(ref _displayName,value);} public string Family{get=>_family;set=>SetProperty(ref _family,value);} public string TubeTypes{get=>_tubeTypes;set=>SetProperty(ref _tubeTypes,value);} public string Manufacturer{get=>_manufacturer;set=>SetProperty(ref _manufacturer,value);} public string? Pinout{get=>_pinout;set=>SetProperty(ref _pinout,value);} public string Warning{get=>_warning;set=>SetProperty(ref _warning,value);}
    public double? HeaterVoltage{get=>_heaterVoltage;set=>SetProperty(ref _heaterVoltage,value);} public double? HeaterCurrentAmp{get=>_heaterCurrent;set=>SetProperty(ref _heaterCurrent,value);} public double? AnodeVoltage{get=>_anodeVoltage;set=>SetProperty(ref _anodeVoltage,value);} public double? ScreenVoltage{get=>_screenVoltage;set=>SetProperty(ref _screenVoltage,value);} public double? GridVoltage{get=>_gridVoltage;set=>SetProperty(ref _gridVoltage,value);} public double? NominalIa{get=>_ia;set=>SetProperty(ref _ia,value);} public double? NominalIs{get=>_is;set=>SetProperty(ref _is,value);} public double? NominalGm{get=>_gm;set=>SetProperty(ref _gm,value);} public double? NominalMu{get=>_mu;set=>SetProperty(ref _mu,value);} public double? NominalRp{get=>_rp;set=>SetProperty(ref _rp,value);} public double? MaxAnodeVoltage{get=>_maxVa;set=>SetProperty(ref _maxVa,value);} public double? MaxScreenVoltage{get=>_maxVs;set=>SetProperty(ref _maxVs,value);} public double? MaxAnodePower{get=>_maxPa;set=>SetProperty(ref _maxPa,value);} public double? MaxScreenPower{get=>_maxPs;set=>SetProperty(ref _maxPs,value);} public double? AnodeCompliance{get=>_iaComp;set=>SetProperty(ref _iaComp,value);} public double? ScreenCompliance{get=>_isComp;set=>SetProperty(ref _isComp,value);} public int? WarmupSeconds{get=>_warmup;set=>SetProperty(ref _warmup,value);} public double? CurveStart{get=>_curveStart;set=>SetProperty(ref _curveStart,value);} public double? CurveStop{get=>_curveStop;set=>SetProperty(ref _curveStop,value);} public double? CurveStep{get=>_curveStep;set=>SetProperty(ref _curveStep,value);} public string? CurveGridVoltages{get=>_curveGrids;set=>SetProperty(ref _curveGrids,value);}
    public string MeasurementPurpose{get=>_purpose;set=>SetProperty(ref _purpose,value);} public string SourceTitle{get=>_sourceTitle;set=>SetProperty(ref _sourceTitle,value);} public string SourceUrl{get=>_sourceUrl;set=>SetProperty(ref _sourceUrl,value);} public string SourcePage{get=>_sourcePage;set=>SetProperty(ref _sourcePage,value);} public string Notes{get=>_notes;set=>SetProperty(ref _notes,value);} public string HeaterSupplyMode{get=>_heaterMode;set=>SetProperty(ref _heaterMode,value);} public string HeaterSupplyNote{get=>_heaterNote;set=>SetProperty(ref _heaterNote,value);} public string Reviewer{get=>_reviewer;set=>SetProperty(ref _reviewer,value);} public string ReviewNote{get=>_reviewNote;set=>SetProperty(ref _reviewNote,value);} public string Status{get=>_status;set=>SetProperty(ref _status,value);}
    public bool SourceIdentityConfirmed{get=>_sourceOk;set=>SetProperty(ref _sourceOk,value);} public bool PinoutConfirmed{get=>_pinoutOk;set=>SetProperty(ref _pinoutOk,value);} public bool HeaterConfirmed{get=>_heaterOk;set=>SetProperty(ref _heaterOk,value);} public bool OperatingPointConfirmed{get=>_pointOk;set=>SetProperty(ref _pointOk,value);} public bool LimitsConfirmed{get=>_limitsOk;set=>SetProperty(ref _limitsOk,value);} public bool PowerGuardConfirmed{get=>_powerOk;set=>SetProperty(ref _powerOk,value);} public bool HardwareConfirmed{get=>_hardwareOk;set=>SetProperty(ref _hardwareOk,value);} public bool HasProfile=>!string.IsNullOrWhiteSpace(ProfileId);

    public void Load(ProfileEditDraft d){ProfileId=d.ProfileId;DisplayName=d.DisplayName;Family=d.Family;TubeTypes=d.TubeTypes;Manufacturer=d.ManufacturerScope;Pinout=d.Pinout;Warning=d.CriticalWarning;HeaterVoltage=d.HeaterVoltage;HeaterCurrentAmp=d.HeaterCurrentAmp;AnodeVoltage=d.AnodeVoltage;ScreenVoltage=d.ScreenVoltage;GridVoltage=d.GridVoltage;NominalIa=d.NominalAnodeCurrentMa;NominalIs=d.NominalScreenCurrentMa;NominalGm=d.NominalGmMaV;NominalMu=d.NominalMu;NominalRp=d.NominalRpKohm;MaxAnodeVoltage=d.MaxAnodeVoltage;MaxScreenVoltage=d.MaxScreenVoltage;MaxAnodePower=d.MaxAnodePowerW;MaxScreenPower=d.MaxScreenPowerW;AnodeCompliance=d.AnodeComplianceMa;ScreenCompliance=d.ScreenComplianceMa;WarmupSeconds=d.WarmupSeconds;CurveStart=d.CurveVaStartV;CurveStop=d.CurveVaStopV;CurveStep=d.CurveVaStepV;CurveGridVoltages=d.CurveGridVoltages;MeasurementPurpose=d.MeasurementPurpose;SourceTitle=d.SourceTitle;SourceUrl=d.SourceUrl;SourcePage=d.SourcePage;Notes=d.Notes;HeaterSupplyMode=d.HeaterSupplyMode;HeaterSupplyNote=d.HeaterSupplyNote;Reviewer=d.Reviewer;ReviewNote=d.ReviewNote;SourceIdentityConfirmed=d.SourceIdentityConfirmed;PinoutConfirmed=d.PinoutConfirmed;HeaterConfirmed=d.HeaterConfirmed;OperatingPointConfirmed=d.OperatingPointConfirmed;LimitsConfirmed=d.LimitsConfirmed;PowerGuardConfirmed=d.PowerGuardConfirmed;HardwareConfirmed=d.HardwareConfirmed;Status=$"Wczytano {d.ProfileId}. Puste pola pozostają puste do ręcznego potwierdzenia.";OnPropertyChanged(nameof(HasProfile));}
    public ProfileEditDraft Build()=>new(){ProfileId=ProfileId,DisplayName=DisplayName,Family=Family,TubeTypes=TubeTypes,ManufacturerScope=Manufacturer,Pinout=Pinout,CriticalWarning=Warning,HeaterVoltage=HeaterVoltage,HeaterCurrentAmp=HeaterCurrentAmp,AnodeVoltage=AnodeVoltage,ScreenVoltage=ScreenVoltage,GridVoltage=GridVoltage,NominalAnodeCurrentMa=NominalIa,NominalScreenCurrentMa=NominalIs,NominalGmMaV=NominalGm,NominalMu=NominalMu,NominalRpKohm=NominalRp,MaxAnodeVoltage=MaxAnodeVoltage,MaxScreenVoltage=MaxScreenVoltage,MaxAnodePowerW=MaxAnodePower,MaxScreenPowerW=MaxScreenPower,AnodeComplianceMa=AnodeCompliance,ScreenComplianceMa=ScreenCompliance,WarmupSeconds=WarmupSeconds,CurveVaStartV=CurveStart,CurveVaStopV=CurveStop,CurveVaStepV=CurveStep,CurveGridVoltages=CurveGridVoltages,MeasurementPurpose=MeasurementPurpose,SourceTitle=SourceTitle,SourceUrl=SourceUrl,SourcePage=SourcePage,Notes=Notes,HeaterSupplyMode=HeaterSupplyMode,HeaterSupplyNote=HeaterSupplyNote,SourceIdentityConfirmed=SourceIdentityConfirmed,PinoutConfirmed=PinoutConfirmed,HeaterConfirmed=HeaterConfirmed,OperatingPointConfirmed=OperatingPointConfirmed,LimitsConfirmed=LimitsConfirmed,PowerGuardConfirmed=PowerGuardConfirmed,HardwareConfirmed=HardwareConfirmed,Reviewer=Reviewer,ReviewNote=ReviewNote};
}
